FROM rocker/verse
MAINTAINER Chao Yuan <yc99731@ad.unc.edu>
RUN apt update && apt-get -y update && apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev libproj-dev
RUN R -e "install.packages(\"tinytex\")"
RUN R -e "install.packages(\"tidyverse\")"
RUN R -e "install.packages(\"jsonlite\")"
RUN R -e "install.packages(\"tidygeocoder\")"
RUN R -e "install.packages(\"fs\")"
RUN R -e "install.packages(\"janitor\")"
RUN R -e "install.packages(\"tidycensus\")"
RUN R -e "install.packages(\"labelled\")"
RUN R -e "install.packages(\"ggExtra\")"
RUN R -e "install.packages(\"patchwork\")"
RUN R -e "install.packages(\"shiny\")"
RUN R -e "install.packages(\"shinythemes\")"
RUN R -e "install.packages(\"dplyr\")"
RUN R -e "install.packages(\"maps\")"
RUN R -e "install.packages(\"ggplot2\")"
RUN R -e "install.packages(\"viridis\")"
RUN R -e "install.packages(\"data.table\")"
RUN R -e "install.packages(\"ggthemes\")"
